# Generated by Django 5.1.15 on 2026-06-24 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpora', '0001_initial'),
        ('projects', '0003_project_locked_project_locked_at_project_locked_by'),
        ('schemes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unresolved', 'Non résolu'), ('in_progress', 'En cours'), ('resolved', 'Résolu')], default='unresolved', max_length=16)),
                ('pct_resolved', models.FloatField(default=0.0)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('arbiters', models.ManyToManyField(blank=True, related_name='gold_arbitrations', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_resolutions', to='corpora.document')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_resolutions', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'document'],
            },
        ),
        migrations.CreateModel(
            name='ArbitrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(blank=True, null=True)),
                ('verb', models.CharField(choices=[('decide', 'Décision'), ('auto', 'Auto-résolution'), ('override', 'Révision'), ('comment', 'Commentaire'), ('lock', 'Verrou'), ('unlock', 'Déverrou'), ('steal', 'Reprise')], max_length=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='gold.goldresolution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoldRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='draft', max_length=8)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='gold.goldresolution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoldSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('agreement_class', models.CharField(choices=[('strict', 'Accord strict'), ('majority', 'Accord majoritaire'), ('divergence', 'Divergence'), ('empty', 'Non couvert')], default='empty', max_length=12)),
                ('risk_band', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='medium', max_length=8)),
                ('auto_level', models.CharField(choices=[('auto_1click', 'Accord absolu (1 clic)'), ('auto', 'Auto (peu risqué)'), ('manual', 'Manuel')], default='manual', max_length=12)),
                ('confidence', models.FloatField(default=0.0)),
                ('human_dissent', models.BooleanField(default=False)),
                ('proposed_primary', models.CharField(blank=True, default='', max_length=60)),
                ('proposed_secondaries', models.JSONField(blank=True, default=list)),
                ('human_block', models.CharField(blank=True, default='', max_length=60)),
                ('llm_block', models.CharField(blank=True, default='', max_length=60)),
                ('tally', models.JSONField(blank=True, default=dict)),
                ('decided', models.BooleanField(default=False)),
                ('auto_resolved', models.BooleanField(default=False)),
                ('secondaries', models.JSONField(blank=True, default=list)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gold_sentences', to='schemes.theme')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='gold.goldresolution')),
            ],
            options={
                'ordering': ['resolution', 'index'],
            },
        ),
        migrations.AddConstraint(
            model_name='goldresolution',
            constraint=models.UniqueConstraint(fields=('project', 'document'), name='uniq_gold_resolution_proj_doc'),
        ),
        migrations.AddConstraint(
            model_name='goldsentence',
            constraint=models.UniqueConstraint(fields=('resolution', 'index'), name='uniq_gold_sentence_res_index'),
        ),
    ]
