# Generated by Django 5.1.15 on 2026-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gold", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arbitrationevent",
            name="verb",
            field=models.CharField(
                choices=[
                    ("decide", "Décision"),
                    ("auto", "Auto-résolution"),
                    ("override", "Révision"),
                    ("comment", "Commentaire"),
                    ("lock", "Verrou"),
                    ("unlock", "Déverrou"),
                    ("steal", "Reprise"),
                    ("finalize", "Soumission de la résolution"),
                    ("reopen", "Réouverture"),
                    ("seed", "Annotateur LLM ajouté/retiré"),
                ],
                max_length=12,
            ),
        ),
    ]
