# Generated by Django 5.1.15 on 2026-06-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpora', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(choices=[('claude', 'Claude'), ('codex', 'Codex'), ('other', 'Other')], max_length=20)),
                ('schema_version', models.CharField(max_length=40)),
                ('raw', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('mapped', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preannotations', to='corpora.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preannotations', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'document', 'judge'],
            },
        ),
        migrations.CreateModel(
            name='PreClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_index', models.PositiveIntegerField()),
                ('theme_code', models.CharField(max_length=60)),
                ('evidence_span', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('preannotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preclauses', to='imports.preannotation')),
            ],
            options={
                'ordering': ['preannotation', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='preannotation',
            constraint=models.UniqueConstraint(fields=('project', 'document', 'judge', 'schema_version'), name='uniq_preannotation_proj_doc_judge_version'),
        ),
    ]
