# Generated by Django 5.1.15 on 2026-06-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preannotation',
            name='judge',
            field=models.CharField(choices=[('claude', 'Claude'), ('codex', 'Codex'), ('mistral', 'Mistral'), ('other', 'Other')], max_length=20),
        ),
    ]
