# Generated by Django 5.1.15 on 2026-06-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_preannotation_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='preclause',
            name='legal_nature',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
