# Generated by Django 5.1.15 on 2026-08-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_preclause_legal_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preannotation',
            name='judge',
            field=models.CharField(choices=[('claude', 'Claude'), ('codex', 'Codex'), ('mistral', 'Mistral'), ('fable', 'Fable'), ('other', 'Other')], max_length=20),
        ),
    ]
