# Generated by Django 5.1.15 on 2026-06-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('definition', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='LegalNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_natures', to='schemes.labelscheme')),
            ],
            options={
                'ordering': ['scheme', 'order'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'code'), name='uniq_legalnature_scheme_code')],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('definition', models.TextField(blank=True)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='schemes.labelscheme')),
            ],
            options={
                'ordering': ['scheme', 'order'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'code'), name='uniq_theme_scheme_code')],
            },
        ),
    ]
