# Generated by Django 5.1.15 on 2026-06-18 14:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corpora', '0001_initial'),
        ('projects', '0001_initial'),
        ('schemes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('global_certainty', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Incertain'), (1, 'Plutôt'), (2, 'Confiant'), (3, 'Certain')], null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('source', models.CharField(choices=[('human', 'Human'), ('preannotation_seed', 'Pre-annotation seed')], default='human', max_length=24)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='corpora.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='annotations.annotation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotation_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['annotation', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_span', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('certainty', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Incertain'), (1, 'Plutôt'), (2, 'Confiant'), (3, 'Certain')], null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('anchor_sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anchored_clauses', to='corpora.sentence')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='annotations.annotation')),
                ('legal_nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='schemes.legalnature')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clauses', to='schemes.theme')),
            ],
            options={
                'ordering': ['annotation', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('project', 'document', 'annotator'), name='uniq_annotation_project_doc_annotator'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.CheckConstraint(condition=models.Q(('global_certainty__isnull', True), ('global_certainty__in', [0, 1, 2, 3]), _connector='OR'), name='ck_annotation_global_certainty_range'),
        ),
        migrations.AddConstraint(
            model_name='annotationversion',
            constraint=models.UniqueConstraint(fields=('annotation', 'number'), name='uniq_version_annotation_number'),
        ),
        migrations.AddConstraint(
            model_name='clause',
            constraint=models.UniqueConstraint(fields=('annotation', 'anchor_sentence'), name='uniq_clause_annotation_anchor'),
        ),
        migrations.AddConstraint(
            model_name='clause',
            constraint=models.CheckConstraint(condition=models.Q(('certainty__isnull', True), ('certainty__in', [0, 1, 2, 3]), _connector='OR'), name='ck_clause_certainty_range'),
        ),
    ]
