# Generated by Django 5.1.15 on 2026-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
        ('corpora', '0001_initial'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='client_op_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='clause',
            constraint=models.UniqueConstraint(condition=models.Q(('client_op_id', ''), _negated=True), fields=('annotation', 'client_op_id'), name='uniq_clause_client_op'),
        ),
    ]
