# Generated by Django 5.1.15 on 2026-06-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_clause_client_op_id_clause_uniq_clause_client_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
