# Generated by Django 5.1.15 on 2026-06-22 21:13

import django.db.models.deletion
from django.db import migrations, models


def backfill_primary_tags(apps, schema_editor):
    """Legacy mono → 1 ClauseTheme primary par clause (rétro-compatibilité)."""
    Clause = apps.get_model("annotations", "Clause")
    ClauseTheme = apps.get_model("annotations", "ClauseTheme")
    to_create = [
        ClauseTheme(clause_id=cid, theme_id=tid, role="primary", support=0, order=0)
        for cid, tid in Clause.objects.values_list("id", "theme_id")
    ]
    ClauseTheme.objects.bulk_create(to_create, batch_size=1000)


def remove_tags(apps, schema_editor):
    apps.get_model("annotations", "ClauseTheme").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_clause_validated'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='boundary_support',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clause',
            name='boundary_type',
            field=models.CharField(choices=[('hard', 'Frontière dure'), ('soft', 'Frontière molle')], default='hard', max_length=4),
        ),
        migrations.AddField(
            model_name='clause',
            name='triage_level',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.CreateModel(
            name='ClauseTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire')], max_length=9)),
                ('support', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_tags', to='annotations.clause')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clause_tags', to='schemes.theme')),
            ],
            options={
                'ordering': ['clause', 'order'],
                'constraints': [models.UniqueConstraint(fields=('clause', 'theme'), name='uniq_clause_theme')],
            },
        ),
        migrations.RunPython(backfill_primary_tags, remove_tags),
    ]
