# Generated by Django 5.1.15 on 2026-06-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationset',
            options={'ordering': ['corpus', 'name']},
        ),
    ]
