# Generated by Django 5.1.15 on 2026-06-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('license', models.CharField(blank=True, max_length=120)),
                ('default_language', models.CharField(default='en', max_length=12)),
            ],
            options={
                'verbose_name_plural': 'corpora',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('language', models.CharField(default='en', max_length=12)),
                ('n_sentences', models.PositiveIntegerField(default=0)),
                ('source_meta', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='corpora.corpus')),
            ],
            options={
                'ordering': ['corpus', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('raw_text', models.TextField()),
                ('clean_text', models.TextField(blank=True)),
                ('char_start', models.PositiveIntegerField(blank=True, null=True)),
                ('char_end', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='corpora.document')),
            ],
            options={
                'ordering': ['document', 'index'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=8)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('source', models.CharField(default='claudette', max_length=60)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_labels', to='corpora.sentence')),
            ],
            options={
                'ordering': ['sentence', 'category'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('corpus', 'external_id'), name='uniq_document_corpus_external'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(fields=('document', 'index'), name='uniq_sentence_document_index'),
        ),
        migrations.AddConstraint(
            model_name='referencelabel',
            constraint=models.UniqueConstraint(fields=('sentence', 'category'), name='uniq_reflabel_sentence_category'),
        ),
    ]
