# Generated by Django 5.1.15 on 2026-08-11 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_locked_project_locked_at_project_locked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('local', 'Local'), ('g5k', "Grid'5000")], default='local', max_length=8)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compute_targets', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('task', models.CharField(choices=[('T1_primary', 'T1 — thème primaire'), ('T2_multilabel', 'T2 — multi-label'), ('T3_boundary', 'T3 — frontières')], default='T1_primary', max_length=16)),
                ('config', models.JSONField(default=dict)),
                ('preset', models.CharField(blank=True, default='', max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('compute_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='lab.computetarget')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('waiting', "En attente d'allocation"), ('running', 'En cours'), ('succeeded', 'Terminé'), ('partial', 'Partiel'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='queued', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('phase', models.CharField(blank=True, default='', max_length=40)),
                ('config', models.JSONField(default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('environment', models.JSONField(blank=True, default=dict)),
                ('external_job_id', models.CharField(blank=True, default='', max_length=80)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('error_detail', models.CharField(blank=True, default='', max_length=500)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='lab.experiment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabDataset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('maturity', models.CharField(choices=[('any', 'Toutes'), ('complete', 'Complètes'), ('submitted', 'Soumises'), ('gold', 'Gold finalisé')], default='complete', max_length=12)),
                ('aggregation', models.CharField(choices=[('single', 'Un annotateur'), ('consensus', 'Consensus (cascade)'), ('soft', 'Soft labels')], default='consensus', max_length=12)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('splits', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('building', 'Construction'), ('ready', 'Prêt'), ('failed', 'Échec')], default='building', max_length=12)),
                ('storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('n_documents', models.PositiveIntegerField(default=0)),
                ('n_sentences', models.PositiveIntegerField(default=0)),
                ('n_annotations', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_datasets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_datasets', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='lab.labdataset'),
        ),
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('figure', 'Figure'), ('table', 'Tableau'), ('model', 'Modèle'), ('predictions', 'Prédictions'), ('errors', "Analyse d'erreurs"), ('log', 'Journal')], max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('mime', models.CharField(blank=True, default='', max_length=80)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='lab.experimentrun')),
            ],
            options={
                'ordering': ['run', 'kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComputeCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('local', 'Local'), ('g5k', "Grid'5000")], default='g5k', max_length=8)),
                ('login', models.CharField(max_length=120)),
                ('secret_encrypted', models.TextField(blank=True, default='')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_detail', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compute_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='uniq_credential_user_kind')],
            },
        ),
        migrations.AddConstraint(
            model_name='computetarget',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_compute_target_name'),
        ),
        migrations.AddIndex(
            model_name='experimentrun',
            index=models.Index(fields=['status', 'created_at'], name='lab_experim_status_d31269_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentrun',
            index=models.Index(fields=['status', 'heartbeat_at'], name='lab_experim_status_fd1843_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentrun',
            index=models.Index(fields=['experiment', 'created_at'], name='lab_experim_experim_7d6d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='labdataset',
            index=models.Index(fields=['project', 'created_at'], name='lab_labdata_project_0ad9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='labdataset',
            index=models.Index(fields=['project', 'fingerprint'], name='lab_labdata_project_f7c747_idx'),
        ),
    ]
