# Generated by Django 5.1.15 on 2026-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computecredential',
            name='last_test_ssh_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computecredential',
            name='ssh_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
