/**
 * Static sections of the reviewer page, rendered on the server from `RELEASE.json`
 * (generated by scripts/build_thematic_layer_release.py — never typed by hand):
 * "What we release", "Key figures", "Protocol", "Codebook".
 */

import { Archive, ExternalLink, FileJson, FileText, Layers, Scale } from "lucide-react";

import { Disclosure } from "@/components/ui/Disclosure";
import { Panel } from "@/components/ui/primitives";
import { T11_EN, T20_EN } from "@/lib/taxonomy/labels.en";
import { formatBytes, formatNumber } from "./logic";

export interface ReleaseDownload {
  name: string;
  path: string;
  bytes: number;
  sha256: string;
  records: number | null;
  description: string;
}

export interface ReleaseFigure {
  key: string;
  label: string;
  t20: number | null;
  t11: number | null;
  source: string;
  how: string;
  extra?: Record<string, number | null>;
}

export interface ReleaseModel {
  checkpoint: string;
  trainedOn: { documents: number | null; population: string };
  evaluatedOn: { documents: number | null; population: string };
  metrics: { macroF1: number | null; microF1: number | null; kappa: number | null; macroF1Ci?: { low: number; high: number } | null };
  recipe: Record<string, string | number>;
}

export interface Release {
  datasetFingerprint: string;
  builtAt: string;
  counts: { documents: number; sentences: number; votes: number; goldSentences: number; annotators: number; judges: string[]; unfairSentences?: number };
  zip: { path: string; bytes: number; sha256: string };
  downloads: ReleaseDownload[];
  judges: Array<{ id: string; model: string }>;
  figures: ReleaseFigure[];
  model: ReleaseModel | null;
}

const CARD_ORDER: Array<{ file: string; title: string; icon: JSX.Element }> = [
  { file: "votes.jsonl", title: "Individual votes", icon: <FileJson size={16} aria-hidden /> },
  { file: "gold.jsonl", title: "Gold standard and arbitration trail", icon: <Scale size={16} aria-hidden /> },
  { file: "judges.jsonl", title: "LLM judges", icon: <FileJson size={16} aria-hidden /> },
  { file: "taxonomies.json", title: "Frozen taxonomies", icon: <Layers size={16} aria-hidden /> },
];

export function DownloadsGrid({ release }: { release: Release }) {
  const byName = new Map(release.downloads.map((d) => [d.name, d]));
  const prompts = release.downloads.filter((d) => d.name.startsWith("prompts/"));
  const short = release.datasetFingerprint.slice(0, 16);
  return (
    <div className="flex flex-col gap-4">
      <p className="text-sm text-ink-muted">
        All files below are the ones every figure of the paper was computed from. Records are keyed by (document, index) and join directly onto
        the CLAUDETTE corpus, whose sentences we do not redistribute. Annotators appear as A1, A2 and A3.
      </p>
      <Panel className="flex flex-wrap items-center justify-between gap-3 p-4" data-testid="release-zip">
        <div className="flex items-center gap-3">
          <Archive size={18} aria-hidden className="text-accent" />
          <div>
            <p className="text-sm font-medium text-ink">Everything in one archive</p>
            <p className="font-mono text-[12px] text-ink-muted">
              thematic-layer-{release.datasetFingerprint.slice(0, 8)}.zip · {formatBytes(release.zip.bytes)} · SHA-256 {release.zip.sha256.slice(0, 16)}…
            </p>
          </div>
        </div>
        <a href={release.zip.path} className="rounded-md bg-accent px-4 py-2 text-sm font-medium text-accent-fg hover:brightness-110" download>
          Download the archive
        </a>
      </Panel>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {CARD_ORDER.map(({ file, title, icon }) => {
          const d = byName.get(file);
          if (!d) return null;
          return (
            <Panel key={file} className="flex flex-col gap-2 p-4" data-testid={`release-card-${file}`}>
              <div className="flex items-center gap-2 text-accent">
                {icon}
                <h3 className="text-sm font-semibold text-ink">{title}</h3>
              </div>
              <p className="text-[13px] text-ink-muted">{d.description}</p>
              <p className="font-mono text-[11px] text-ink-muted">
                {d.name} · {d.records ? `${d.records.toLocaleString("en-GB")} records · ` : ""}
                {formatBytes(d.bytes)}
              </p>
              <a href={d.path} download className="mt-auto text-sm font-medium text-accent hover:underline">
                Download
              </a>
            </Panel>
          );
        })}
        <Panel className="flex flex-col gap-2 p-4" data-testid="release-card-prompts">
          <div className="flex items-center gap-2 text-accent">
            <FileText size={16} aria-hidden />
            <h3 className="text-sm font-semibold text-ink">Judge prompts</h3>
          </div>
          <p className="text-[13px] text-ink-muted">
            The instruction files given to the judges (protocol v9.2) and the session protocol: inputs, isolation, validation, models,
            harnesses and dates for {release.judges.map((j) => j.model).join(", ")}.
          </p>
          <ul className="mt-auto flex flex-col gap-0.5 text-[12px]">
            {prompts.map((p) => (
              <li key={p.name}>
                <a href={p.path} className="font-mono text-accent hover:underline" target="_blank" rel="noreferrer">
                  {p.name.replace("prompts/", "")}
                </a>
              </li>
            ))}
          </ul>
        </Panel>
        <Panel className="flex flex-col gap-2 p-4">
          <div className="flex items-center gap-2 text-accent">
            <FileText size={16} aria-hidden />
            <h3 className="text-sm font-semibold text-ink">Codebook</h3>
          </div>
          <p className="text-[13px] text-ink-muted">The 20 themes with their definitions, the segmentation and multi-label rules given to annotators.</p>
          <a href="#codebook" className="mt-auto text-sm font-medium text-accent hover:underline">
            Read
          </a>
        </Panel>
        <Panel className="flex flex-col gap-2 p-4">
          <div className="flex items-center gap-2 text-accent">
            <FileText size={16} aria-hidden />
            <h3 className="text-sm font-semibold text-ink">Protocol</h3>
          </div>
          <p className="text-[13px] text-ink-muted">Independent annotation, isolated judges, three-tier resolution cascade, read-time projections, document-level bootstrap.</p>
          <a href="#protocol" className="mt-auto text-sm font-medium text-accent hover:underline">
            Read
          </a>
        </Panel>
        <Panel className="flex flex-col gap-2 p-4">
          <div className="flex items-center gap-2 text-accent">
            <ExternalLink size={16} aria-hidden />
            <h3 className="text-sm font-semibold text-ink">Annotation platform</h3>
          </div>
          <p className="text-[13px] text-ink-muted">Source on GitHub, running instance (sign in), public projects.</p>
          <a href="#platform" className="mt-auto text-sm font-medium text-accent hover:underline">
            Open
          </a>
        </Panel>
      </div>
      <p className="text-[12px] text-ink-muted">
        Manifest, labels and splits are included in the archive. Dataset fingerprint {short}… · built {release.builtAt.slice(0, 10)}.
      </p>
    </div>
  );
}

export function KeyFigures({ release }: { release: Release }) {
  return (
    <div className="flex flex-col gap-3">
      <p className="text-sm text-ink-muted">Generated from the released files; open “how computed” for the source of each number.</p>
      <div className="overflow-x-auto">
        <table className="w-full min-w-[40rem] text-sm" data-testid="key-figures">
          <thead>
            <tr className="border-b border-line text-left text-[12px] uppercase tracking-wide text-ink-muted">
              <th className="py-2 pr-3 font-medium">Measure</th>
              <th className="py-2 pr-3 text-right font-medium">20 themes</th>
              <th className="py-2 pr-3 text-right font-medium">11 themes</th>
              <th className="py-2 font-medium">How computed</th>
            </tr>
          </thead>
          <tbody>
            {release.figures.map((f) => (
              <tr key={f.key} className="border-b border-line/60 align-top">
                <td className="py-2 pr-3 text-ink">{f.label}</td>
                <td className="py-2 pr-3 text-right font-mono text-ink">{formatNumber(f.t20)}</td>
                <td className="py-2 pr-3 text-right font-mono text-ink">
                  {formatNumber(f.t11)}
                  {f.extra?.kappa !== undefined && f.extra?.kappa !== null ? ` / κ ${formatNumber(f.extra.kappa)}` : ""}
                </td>
                <td className="py-2 text-[13px] text-ink-muted">
                  <Disclosure summary="how computed" testId={`figure-${f.key}`}>
                    <p>{f.how}</p>
                    <p className="mt-1 font-mono text-[11px]">{f.source}</p>
                  </Disclosure>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {release.model && (
        <Panel className="p-4 text-sm" data-testid="model-card">
          <h3 className="font-semibold text-ink">The model behind “Try the classifier”</h3>
          <p className="mt-1 text-ink-muted">
            {release.model.checkpoint}, fine-tuned once on the {release.model.trainedOn.population} with the paper&apos;s recipe (
            {Object.entries(release.model.recipe)
              .map(([k, v]) => `${k} ${v}`)
              .join(", ")}
            ) and evaluated on the {release.model.evaluatedOn.population}: macro-F1 {formatNumber(release.model.metrics.macroF1)}
            {release.model.metrics.macroF1Ci ? ` [${formatNumber(release.model.metrics.macroF1Ci.low)}; ${formatNumber(release.model.metrics.macroF1Ci.high)}]` : ""}, κ{" "}
            {formatNumber(release.model.metrics.kappa)}.
          </p>
        </Panel>
      )}
    </div>
  );
}

export function Protocol() {
  return (
    <div className="prose-sm max-w-reading text-[15px] leading-reading text-ink">
      <p>
        All 50 English contracts of CLAUDETTE (9,414 sentences) were labelled independently by three trained annotators working from a written
        codebook, with one primary theme and zero or more secondary themes from a closed 20-theme vocabulary. Four large language models labelled
        the same sentences in isolated sessions and were kept out of the reference. The gold standard is resolved strictly between annotators by a
        three-tier cascade: strict agreement, majority of two, human arbitration for the remainder. Coarser taxonomies are deterministic projections
        applied at read time, so every comparison is paired by construction; confidence intervals come from bootstrap resampling over documents. The
        merges were designed on 33 contracts and validated on the 17 held out from that design.
      </p>
    </div>
  );
}

export function Codebook() {
  return (
    <div className="flex flex-col gap-4 text-sm">
      <p className="text-ink-muted">
        Twenty themes, one primary theme per sentence, secondary themes when a sentence genuinely does two things. A theme change starts a new
        clause.
      </p>
      <div className="grid gap-x-8 gap-y-1 sm:grid-cols-2">
        {Object.entries(T20_EN).map(([code, t]) => (
          <div key={code} className="flex flex-col py-1">
            <span className="font-medium text-ink">
              {t.label} <span className="font-mono text-[11px] text-ink-muted">{code}</span>
            </span>
            <span className="text-[13px] text-ink-muted">{t.definition}</span>
          </div>
        ))}
      </div>
      <h4 className="mt-2 font-semibold text-ink">The 11-theme consolidation</h4>
      <div className="grid gap-x-8 gap-y-1 sm:grid-cols-2">
        {Object.entries(T11_EN).map(([code, t]) => (
          <div key={code} className="flex flex-col py-1">
            <span className="font-medium text-ink">
              {t.label} <span className="font-mono text-[11px] text-ink-muted">{code}</span>
            </span>
            <span className="text-[13px] text-ink-muted">{t.definition}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
