# Generated by Django 5.1.15 on 2026-07-22 09:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0003_project_locked_project_locked_at_project_locked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("personal", "Personnel"), ("project", "Projet")],
                        default="personal",
                        max_length=12,
                    ),
                ),
                ("includes_drafts", models.BooleanField(default=True)),
                ("scope", models.JSONField(default=dict)),
                ("manifest", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("document_count", models.PositiveIntegerField(default=0)),
                ("annotation_count", models.PositiveIntegerField(default=0)),
                ("draft_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_snapshots",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("metric_codes", models.JSONField(default=list)),
                ("metric_versions", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En attente"),
                            ("running", "En cours"),
                            ("succeeded", "Terminé"),
                            ("failed", "Échec"),
                            ("stale", "Obsolète"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("result", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("error_code", models.CharField(blank=True, default="", max_length=60)),
                ("error_detail", models.CharField(blank=True, default="", max_length=500)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_runs",
                        to="projects.project",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="analysis.analysissnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("personal", "Personnel"), ("project", "Projet")],
                        default="personal",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "Disponible"), ("archived", "Archivé")],
                        default="ready",
                        max_length=12,
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                ("summary", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_reports",
                        to="projects.project",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="analysis.analysisrun",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="analysis.analysissnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="analysissnapshot",
            index=models.Index(
                fields=["project", "created_at"], name="analysis_an_project_f52530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysissnapshot",
            index=models.Index(
                fields=["project", "visibility", "created_at"],
                name="analysis_an_project_c52564_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["project", "status", "created_at"], name="analysis_an_project_3c0cf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["snapshot", "created_at"], name="analysis_an_snapsho_bf93e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisreport",
            index=models.Index(
                fields=["project", "status", "created_at"], name="analysis_an_project_0a1812_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisreport",
            index=models.Index(
                fields=["project", "visibility", "created_at"],
                name="analysis_an_project_cc764c_idx",
            ),
        ),
    ]
