# Generated by Django 5.1.15 on 2026-07-22 09:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
        ("projects", "0003_project_locked_project_locked_at_project_locked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="attempt",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="cancel_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="configuration",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="analysisrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "En attente"),
                    ("running", "En cours"),
                    ("succeeded", "Terminé"),
                    ("failed", "Échec"),
                    ("stale", "Obsolète"),
                    ("canceled", "Annulé"),
                ],
                default="queued",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="AnalysisPreset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("configuration", models.JSONField(default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_presets",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "created_by", "name"),
                        name="uniq_analysis_preset_owner_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnalysisReportArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En attente"),
                            ("running", "En cours"),
                            ("ready", "Disponible"),
                            ("failed", "Échec"),
                            ("expired", "Expiré"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=700)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("manifest", models.JSONField(default=dict)),
                ("error_detail", models.CharField(blank=True, default="", max_length=500)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="analysis.analysisreport",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_report_artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="analysis_an_status_c9d8f5_idx"
                    )
                ],
            },
        ),
    ]
