# Generated by Django 5.1.15 on 2026-07-22 10:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_analysisrun_attempt_analysisrun_cancel_requested_and_more"),
        ("projects", "0003_project_locked_project_locked_at_project_locked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisTaxonomyProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("theme_code", models.CharField(blank=True, default="", max_length=60)),
                ("title", models.CharField(max_length=200)),
                ("rationale", models.TextField(blank=True, default="")),
                ("evidence", models.JSONField(default=dict)),
                ("status", models.CharField(default="draft", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_taxonomy_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_taxonomy_proposals",
                        to="projects.project",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="taxonomy_proposals",
                        to="analysis.analysisreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status", "created_at"],
                        name="analysis_an_project_d28285_idx",
                    )
                ],
            },
        ),
    ]
