# Generated by Django 5.1.15 on 2026-07-22 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_analysistaxonomyproposal"),
        ("projects", "0003_project_locked_project_locked_at_project_locked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analysisreportartifact",
            index=models.Index(
                fields=["status", "expires_at"], name="analysis_an_status_44a578_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["status", "created_at"], name="analysis_an_status_7c140b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["status", "heartbeat_at"], name="analysis_an_status_ebc927_idx"
            ),
        ),
    ]
