# Generated by Django 5.1.15 on 2026-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ui_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
