# Generated by Django 5.1.15 on 2026-06-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='format',
            field=models.CharField(choices=[('jsonl', 'JSONL'), ('csv', 'CSV'), ('conll', 'CoNLL'), ('xml', 'XML'), ('md', 'Markdown'), ('huggingface', 'HuggingFace'), ('iaa_matrix', 'Matrice de concordance (IAA)')], max_length=20),
        ),
    ]
