# Generated by Django 5.1.15 on 2026-06-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_alter_exportjob_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
