# Generated by Django 5.1.15 on 2026-09-19 20:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('text', 'Texte collé ou déposé'), ('contract', "Contrat CLAUDETTE tenu à l'écart")], max_length=12)),
                ('document', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('running', 'En cours'), ('done', 'Terminé'), ('failed', 'Échec')], default='queued', max_length=12)),
                ('n_chars', models.PositiveIntegerField(default=0)),
                ('n_sentences', models.PositiveIntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('client_hash', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='demo_demojo_status_64d74a_idx')],
            },
        ),
    ]
